Задание 1

In [2]:
import numpy as np

In [9]:
x = np.arange(10)
y = x[::-1]

In [10]:
y

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [11]:
type(y)

numpy.ndarray

Задание 2

In [12]:
xx = np.arange(15)

In [16]:
yy = xx[::-1]

In [19]:
yy_diag = np.diag(yy)

In [20]:
yy_diag

array([[14,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [21]:
np.trace(yy_diag)

105

Задание 3

In [22]:
import pandas as pd

In [26]:
hw_df = pd.read_csv('ratings.csv')

In [37]:
hw_df[(hw_df['rating']==5 )]['movieId'].value_counts().idxmax()

318

Задание 4

In [38]:
import pandas as pd

In [46]:
z4_df = pd.read_csv('power.csv')
z4_df[ z4_df['country'].str.contains('at', case=False)]['country'].unique()

array(['United States', 'Croatia', 'Latvia', 'United Arab Emirates',
       'Russian Federation', 'Bolivia (Plur. State of)', 'Guatemala',
       'Kiribati', 'Equatorial Guinea', 'State of Palestine',
       'Bonaire, St Eustatius, Saba', 'Qatar', 'Vanuatu',
       'Micronesia (Fed. States of)', 'Montserrat',
       'United States Virgin Is.',
       'Commonwealth of Independent States (CIS)'], dtype=object)

In [51]:
f_z4df = z4_df[(z4_df['country'] == 'Lithuania') | (z4_df['country'] == 'Latvia') | (z4_df['country'] == 'Estonia')]

In [59]:
f2_z4df = f_z4df[(f_z4df['category'] == 4) | (f_z4df['category'] == 12) | (f_z4df['category'] == 21) & (f_z4df['quantity'] > 0)]

In [69]:
f3_z4df = f2_z4df[(f2_z4df['year'] <= 2010) & (f2_z4df['year'] >= 2005)]

In [71]:
f3_z4df['quantity'].sum()

240481.0

Задание 5

In [4]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [6]:
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [7]:
np.allclose(np.dot(a, linalg.solve(a, b)),b)

True